### 获取学生信息（GET）
GET http://localhost:8082/api/getStudent/1
### 更新学生信息（PUT）
PUT http://localhost:8082/api/updatestudent/1
Content-Type: application/json

{
  "id": 1,
  "name": "新的000000",
  "age": 25,
  "grade": "A"
}
### 删除学生信息（DELETE）
DELETE http://localhost:8082/api/delstudent/1
### 获取所有学生信息（GET）
GET http://localhost:8082/api/queryall
### 插入新的学生信息（POST）
POST http://localhost:8082/api/inserStudent
Content-Type: application/json

{
  "name": "新的老师"
}
### 一对多（GET）
GET http://localhost:8082/api/getcourseWithStudentById/2
### 多对多
GET http://localhost:8082/api/getcourseWithTeacherById/1