server:
  port: 8082
  servlet:
    context-path: /api
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3308/user?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&serverTimezone=UTC
mybatis:
    type-aliases-package: com.example.lfj
    mapper-locations: classpath:mapper/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl